grav/user/themes/azul/src/sass/partials/_base.scss, grav/user/themes/azul/src/sass/partials/components/categories-list/_index.scss, grav/user/themes/azul/src/sass/partials/components/title-subcategories/_index.scss
Review /inicio 
the part of the category list is already responsive
max-width: 1280px
max-width: 800px
max-width: 600px
max-width: 100%
=> Adding category list responsive

grav/user/themes/azul/src/sass/partials/components/intro-bae/_index.scss
Intro section BAE Responsive 
Max-width: 1280px
Max-width: 800px
Max-width: 600px
Max-width: 520px
Max-width: 100%
=> Add intro BAE Responsive

grav/user/themes/azul/img/arrow-blue-buttons.svg, grav/user/themes/azul/img/arrow-green-buttons.svg, grav/user/themes/azul/img/arrow-white-buttons.svg, grav/user/themes/azul/src/sass/partials/components/buttons/_index.scss, grav/user/themes/azul/src/sass/partials/components/winners-page/_index.scss, grav/user/themes/azul/templates/winners.html.twig
BA-35
Los botones se tienen que ver asi (tomar en cuenta que los tamaños de letra todavia no estan corregidos)
=> Add border and arrows in buttons

grav/user/pages/05.galardonados/winners.es.md, grav/user/themes/azul/blueprints/winners.yaml, grav/user/themes/azul/src/sass/partials/_base.scss, grav/user/themes/azul/src/sass/partials/components/winners-page/_index.scss, grav/user/themes/azul/templates/winners.html.twig
/galardonados
section responsive
320px
520px
600px
800px
1280px
=> Part responsive of section Impacto

grav/user/pages/06.casos-de-exito/success-story.es.md, grav/user/themes/azul/blueprints/success-story.yaml, grav/user/themes/azul/src/sass/partials/_base.scss, grav/user/themes/azul/src/sass/partials/components/success-story/_index.scss, grav/user/themes/azul/templates/success-story.html.twig
/Casos de Exito
320px
600px
800px
1250px
=> Responsive section success story

grav/user/themes/azul/src/sass/partials/_base.scss, grav/user/themes/azul/src/sass/partials/components/success-story/_index.scss
=> fixed success story

grav/user/themes/azul/src/sass/partials/components/main-footer/_index.scss
poorly accommodated
already fixed
=> fixed footer

grav/user/themes/azul/src/sass/partials/components/main-header/_index.scss
=> Fix issue in header, size 1280px

grav/user/themes/azul/src/sass/partials/components/section-contact/_index.scss, grav/user/themes/azul/src/sass/partials/components/section-contact/section-contact.html, grav/user/themes/azul/templates/own-contact.html.twig, grav/user/themes/azul/templates/partials/base.html.twig
/Contacto
Section Responsive 'Contacto'
320px
600px
1280px
=> responsive section contact

grav/user/themes/azul/js/azul.js, grav/user/themes/azul/src/sass/partials/components/main-header/_index.scss, grav/user/themes/azul/src/sass/partials/components/tabs/_index.scss, grav/user/themes/azul/templates/partials/navigation.html.twig
Fix Header and Tabs section, active class.
=> Fix issue active class in tab and header section

grav/user/themes/azul/src/sass/partials/components/category-page/_index.scss, grav/user/themes/azul/src/sass/partials/components/section-pattern/_index.scss
**Desktop**
**iPad Pro**
**iPad**
**mobile**
=> BA-25 header categories, fix design and responsive

grav/user/themes/azul/js/azul.js, grav/user/themes/azul/js/jquery.quicksand.js, grav/user/themes/azul/src/sass/partials/components/card-categories/_index.scss
Fix card categories responsive
=> Fix filter categories cards

grav/user/themes/azul/src/sass/partials/components/success-story/_index.scss
=> removed unnecessary margin

grav/user/themes/azul/src/sass/partials/components/section-pattern/_index.scss, grav/user/themes/azul/src/sass/partials/components/winners-page/_index.scss
**Desktop**
**iPad Pro**
**iPad**
**Mobile**
=> BA-40 Feature/responsive header winners

grav/user/themes/azul/src/sass/partials/components/winners-page/_index.scss
/Galardonados
320px
600px
800px
1250px
=> fixed section green in galardonados

grav/user/pages/01.inicio/_inicio/intro-home.es.md, grav/user/themes/azul/blueprints/modular/intro-home.yaml, grav/user/themes/azul/src/sass/partials/components/buttons/_index.scss, grav/user/themes/azul/src/sass/partials/components/categories-list/_index.scss, grav/user/themes/azul/templates/modular/intro-home.html.twig
Small Size:
Medium Size:
Large Size:
X-large size:
=> Add intro jump categories page

grav/user/themes/azul/src/sass/partials/components/main-header/main-header.html, grav/user/themes/azul/templates/modular/success-story-item.html.twig, grav/user/themes/azul/templates/partials/base.html.twig, grav/user/themes/azul/templates/success-story.html.twig
=> BA-44 add correction of orthography

grav/user/themes/azul/src/sass/partials/components/category-page/_index.scss, grav/user/themes/azul/templates/category-page.html.twig
BA-44 
Small Size:
Medium Size:
Large Size:
X-large Size:
=> BA-44 - Responsive filter categories

grav/user/pages/01.inicio/_historia-de-exito/success-story-item.es.md, grav/user/themes/azul/blueprints/modular/success-story-item.yaml, grav/user/themes/azul/src/sass/partials/components/success-story-item/_index.scss, grav/user/themes/azul/templates/modular/success-story-item.html.twig
IN PROCESS
/Home
Section Responsives
320px
600px
800px
1250px
=> Section Responsive Success Items

grav/user/themes/azul/src/sass/partials/components/categories-list/_index.scss, grav/user/themes/azul/src/sass/partials/components/success-story-item/_index.scss
Jump to category page
Small Size:
Medium Size:
Large Size:
X-Large Size:
=> Fix jump to categories section

grav/user/pages/01.inicio/_inicio/intro-home.es.md, grav/user/themes/azul/src/sass/partials/components/intro-bae/_index.scss
Fix buttons intro home
Small Size:
Medium Size:
Large Size:
X-Large Size:
=> Fix btns intro home

grav/user/themes/azul/src/sass/partials/components/category-page/_index.scss
**Desktop**
**iPad pro**
**iPad**
**Mobile**
=> BA-48 Feature/responsive header nodo categories

grav/user/themes/azul/blueprints/categories.yaml, grav/user/themes/azul/src/sass/partials/components/step-item/_index.scss, grav/user/themes/azul/templates/categories.html.twig
/Categorías
adding new step item
Example:
Inside Grav:
=> New step item

grav/user/themes/azul/src/sass/partials/components/section-allies/_index.scss
=> BA-59 add changes width of logos

grav/user/themes/azul/src/sass/partials/components/winners-page/_index.scss, grav/user/themes/azul/templates/winners.html.twig
=> Add Winners drive link

grav/user/themes/azul/src/sass/partials/components/categories-list/_index.scss, grav/user/themes/azul/src/sass/partials/components/intro-bae/_index.scss, grav/user/themes/azul/src/sass/partials/components/success-story-item/_index.scss
=> BA-51 margenes en home

grav/user/themes/azul/blueprints/categories.yaml, grav/user/themes/azul/src/sass/partials/components/category-page/_index.scss, grav/user/themes/azul/templates/categories.html.twig, grav/user/themes/azul/templates/category-page.html.twig
=> add changes in categories items BA-58

grav/user/themes/azul/blueprints/categories.yaml, grav/user/themes/azul/src/sass/partials/components/step-item/_index.scss, grav/user/themes/azul/templates/categories.html.twig
Steps buttons in category works and download .doc,.docx,.xml,.pdf,.ppt files...
=> Fix download btns in categories

grav/user/themes/azul/src/sass/partials/components/category-page/_index.scss, grav/user/themes/azul/templates/categories.html.twig
=> fix coordinador

grav/user/config/site.yaml
=> config site
